<a href="https://colab.research.google.com/github/sergey031/DZ_MLP/blob/master/%C3%90%C2%9F%C3%90%C2%A0_1_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практическая работа 1-1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy
numpy.__version__

'1.23.5'

2) Создать нулевой вектор размера 10

In [ ]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
import numpy as np

vector = np.full(7, 7)
print(vector)

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
import numpy as np

start = 10
end = 100
step = 2

vector = np.arange(start, end + 1, step)
print(vector)


[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
import numpy as np

random_array = np.random.randint(0, 101, 10)
print(random_array)

reversed_array = random_array[::-1]
print(reversed_array)


[37 16 23 93 59 62 27 87 97 49]
[49 97 87 27 62 59 93 23 16 37]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
import numpy as np

matrix = np.zeros((4, 4), dtype=int)

np.fill_diagonal(matrix[1:], 1)

print(matrix)


[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


*8*) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
import numpy as np

matrix = np.full((4, 4), 7)
for i in range(4):
    matrix[i, i] = i + 1
print(matrix)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
import numpy as np

matrix = np.empty((5, 5), dtype=int)
for i in range(5):
    matrix[i] = np.arange(5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
import numpy as np

matrix = np.random.randint(0, 10, (10, 10))
row_means = np.mean(matrix, axis=1, keepdims=True)
normalized_matrix = matrix - row_means

print(matrix)
print(normalized_matrix)

[[0 1 5 2 3 8 1 7 2 4]
 [7 1 6 7 1 3 6 1 3 5]
 [8 8 0 1 3 1 1 2 5 5]
 [1 6 6 7 9 8 2 5 8 3]
 [5 7 3 8 4 4 3 2 0 5]
 [7 1 0 3 6 0 0 5 0 7]
 [7 1 7 7 2 4 2 7 8 8]
 [7 9 4 0 6 0 3 4 5 6]
 [4 8 5 2 5 5 4 7 3 7]
 [6 3 9 8 7 5 1 3 2 2]]
[[-3.3 -2.3  1.7 -1.3 -0.3  4.7 -2.3  3.7 -1.3  0.7]
 [ 3.  -3.   2.   3.  -3.  -1.   2.  -3.  -1.   1. ]
 [ 4.6  4.6 -3.4 -2.4 -0.4 -2.4 -2.4 -1.4  1.6  1.6]
 [-4.5  0.5  0.5  1.5  3.5  2.5 -3.5 -0.5  2.5 -2.5]
 [ 0.9  2.9 -1.1  3.9 -0.1 -0.1 -1.1 -2.1 -4.1  0.9]
 [ 4.1 -1.9 -2.9  0.1  3.1 -2.9 -2.9  2.1 -2.9  4.1]
 [ 1.7 -4.3  1.7  1.7 -3.3 -1.3 -3.3  1.7  2.7  2.7]
 [ 2.6  4.6 -0.4 -4.4  1.6 -4.4 -1.4 -0.4  0.6  1.6]
 [-1.   3.   0.  -3.   0.   0.  -1.   2.  -2.   2. ]
 [ 1.4 -1.6  4.4  3.4  2.4  0.4 -3.6 -1.6 -2.6 -2.6]]


*11*) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
import numpy as np

matrix = np.random.randint(0, 100, (10, 10))
column_medians = np.median(matrix, axis=0, keepdims=True)
normalized_matrix = matrix - column_medians

print(matrix)
print(normalized_matrix)

[[52 16 12 55 72 27 49 14 65 17]
 [75 85 18 81 21 12 28 29 16  1]
 [ 5  9 21 88 70 64 79 98 84 53]
 [ 5 92 87 37 96 85 12 23 56 81]
 [45 76 75 34 93 82 13  4 69 40]
 [99 97 25 52 86 42 62 64 86 67]
 [98 73 24 77 50 33  6 89  5  3]
 [79 74 56 32 83 76 70 78 76 14]
 [66  2 99 31 61 82 36 41 26 60]
 [84 36 25 50 86 91 28 25 10 10]]
[[-18.5 -57.5 -13.    4.   -5.5 -43.   17.  -21.    4.5 -11.5]
 [  4.5  11.5  -7.   30.  -56.5 -58.   -4.   -6.  -44.5 -27.5]
 [-65.5 -64.5  -4.   37.   -7.5  -6.   47.   63.   23.5  24.5]
 [-65.5  18.5  62.  -14.   18.5  15.  -20.  -12.   -4.5  52.5]
 [-25.5   2.5  50.  -17.   15.5  12.  -19.  -31.    8.5  11.5]
 [ 28.5  23.5   0.    1.    8.5 -28.   30.   29.   25.5  38.5]
 [ 27.5  -0.5  -1.   26.  -27.5 -37.  -26.   54.  -55.5 -25.5]
 [  8.5   0.5  31.  -19.    5.5   6.   38.   43.   15.5 -14.5]
 [ -4.5 -71.5  74.  -20.  -16.5  12.    4.    6.  -34.5  31.5]
 [ 13.5 -37.5   0.   -1.    8.5  21.   -4.  -10.  -50.5 -18.5]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
import numpy as np

matrix = np.random.randint(0, 100, (5, 5))
max_column = np.max(matrix, axis=1, keepdims=True)
min_column = np.min(matrix, axis=1, keepdims=True)
result_matrix = np.hstack((matrix, min_column, max_column))

print(matrix)
print(result_matrix)

[[18 74 40 39 85]
 [44 42 36 25 97]
 [33 63 70 39 17]
 [66 20  1 24 77]
 [38 68 90 85 61]]
[[18 74 40 39 85 18 85]
 [44 42 36 25 97 25 97]
 [33 63 70 39 17 17 70]
 [66 20  1 24 77  1 77]
 [38 68 90 85 61 38 90]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [34]:
import numpy as np

vector = np.arange(1, 52)

odd_vector = vector[vector % 2 != 0]
even_vector = vector[vector % 2 == 0]

odd_matrix = odd_vector[:25].reshape(5, 5)
even_matrix = even_vector[:25].reshape(5, 5)
print(odd_matrix)
print(even_matrix)

min_values = np.min(odd_matrix, axis=1)
max_values = np.max(odd_matrix, axis=1)

odd_matrix_with_ext = np.column_stack((odd_matrix, min_values, max_values))
print(odd_matrix_with_ext)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[ 1  3  5  7  9  1  9]
 [11 13 15 17 19 11 19]
 [21 23 25 27 29 21 29]
 [31 33 35 37 39 31 39]
 [41 43 45 47 49 41 49]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [35]:
import numpy as np

matrix = np.zeros((8, 8), dtype=int)

matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
